# class Persona:

    piernas=2
    brazos=2
    
    def __init__(self, nombre, edad):

        self.mi_nombre=nombre
        self.mi_edad=edad

    def dame_numero_extremidades(self):

        return self.brazos + self.piernas

    def me_presento(self, idioma='español'):

        if idioma=='español':

            print('Mi nombre es', self.mi_nombre)

        elif idioma=='ingles':

            print('My name is', self.mi_nombre)

        else:

            print('no hablo', idioma)

jugador_1 = Persona('Lola', 35)
jugador_2 = Persona('Juan', 45)

In [3]:
type(jugador_1)

__main__.Persona

In [4]:
jugador_1.mi_edad

35

In [5]:
jugador_1.me_presento(idioma='coreano')

no hablo coreano


In [ ]:
jugador_2.me_presento()

In [11]:
mapa = [['a','b'],['c','d']]

In [33]:
len(mapa[1])

2

In [24]:
mapa[1][[0,1]]

TypeError: list indices must be integers or slices, not list

In [25]:
import numpy as np

In [43]:
matriz=np.zeros([3,3])

In [44]:
matriz.dtype

dtype('float64')

In [45]:
matriz.shape

(3, 3)

In [46]:
matriz[0,0]=34
matriz[0,2]=10
matriz[1,2]=5


In [47]:
matriz

array([[34.,  0., 10.],
       [ 0.,  0.,  5.],
       [ 0.,  0.,  0.]])

In [54]:
matriz.diagonal()

array([34.,  0.,  0.])

In [42]:
matriz[:,:]

array([[34., 10.],
       [ 0.,  5.]])

In [ ]:
mi_matriz = np.zeros((3,4), dtype=int)

In [ ]:
type(mi_matriz)

In [ ]:
mi_matriz